### ISSUE TITLE
Use KSP for multiplatform codegen

### ISSUE THREAD

**Issue by Virelion** [pegasystems/mmock#6]

**Comment by Virelion** [comment]
Blocked by: https://github.com/android/kotlin/issues/115

**Comment by Virelion** [comment]
branch: https://github.com/pegasystems/mmock/tree/new-codegen

**Comment by Virelion** [comment]
KSP issue for multiplatform endend up in 2021Q1 milestone.
I will consider making contribution there to speed up some things

**Comment by kamilr12** [comment]
Is it still impossible to use KSP here?

**Comment by Virelion** [comment]
Yesterday I upgraded Kotlin and KSP versions. New feature allowed for turning off incremental compilation that was causing trouble, but there are other errors that made it impossible to use in Kotlin multiplatform

**Comment by Virelion** [comment]
I created PR to KSP https://github.com/google/ksp/pull/243 to fix last issue that is preventing usage of it.
I will prepare this branch for new KSP release (with merged fix).
